[aaron.j] 방탈출 예약관리 3단계
next-step/spring-roomesacpe-reservation-kakao pull request #103
Opened 2023-01-18 09:03 UTC by sgcs11

피드백 반영하여 리뷰 요청드립니다.

사용되지 않는 코드라는 경고가 뜨지만 reflection에서 쓰이는 NoArgsConstructor 등에는 주석으로 표시해 두고 나머지 안 쓰이는 코드는 제거했습니다.

예외를 던지는 코드도 서비스로 옮겼습니다. 이때 spring에서 translate해주는 

DuplicateKeyException, DataIntegrityViolationException이 다른 명칭으로 바뀌는 등 변경된다면, service코드도 변경되므로
해당 도메인 service를 가져다 쓰는 service들에도 영향이 미칠 수 있을 듯 합니다. 
그래서 proxy 객체를 만들고 예외에 대한 처리는 proxy 객체에서 하게 만들면, 예외들이 변경되도 proxy객체만 수정 후 잘 동작하는지 확인할 수 있을 것이라고 생각하는데 어떻게 생각하시는지 궁금합니다.
또, 미션이 아니라 실무라면 어떻게 처리하는 것이 좋은지도 궁금합니다.

감사합니다!!

2023-01-18 10:29 UTC, sgcs11 commented
위에서 말씀드린 JDK dynamic proxy 적용해봤는데 문제가 있다면 revert하겠습니다.

2023-01-19 01:34 UTC, prostars requested changes
몇 가지 코멘트를 했습니다. 확인 바랍니다.
아래는 문의 하신 내용의 답변입니다.

Q: 예외를 던지는 코드도 서비스로 옮겼습니다. 이때 spring에서 translate해주는
DuplicateKeyException, DataIntegrityViolationException이 다른 명칭으로 바뀌는 등 변경된다면, service코드도 변경되므로 해당 도메인 service를 가져다 쓰는 service들에도 영향이 미칠 수 있을 듯 합니다. 그래서 proxy 객체를 만들고 예외에 대한 처리는 proxy 객체에서 하게 만들면, 예외들이 변경되도 proxy객체만 수정 후 잘 동작하는지 확인할 수 있을 것이라고 생각하는데 어떻게 생각하시는지 궁금합니다. 또, 미션이 아니라 실무라면 어떻게 처리하는 것이 좋은지도 궁금합니다.
감사합니다!

A: 스프링 기반으로 작업 중에 스프링이 클래스 명을 바꾸는 것을 걱정하시는 것은 좀 과합니다. 그리고, 그 대응으로 2개의 예외처리를 위해서 proxy를 도입해서 추가적인 aop를 적용하는 것도 과하다고 생각합니다. 가독성이 떨어집니다. 스프링의 DuplicateKeyException을 사용하는 것이 우려되는 상황이라면 java.sql 패키지에 있는 SQL 예외 클래스들 중 적당한 것을 상속받아 구현하고 인프라스트럭처에 두는 방법도 있습니다. 의존 방향은 서비스 -> 인프라스트럭처가 유지됩니다.
step2에서 도메인 관련 예외를 인프라스트럭처에서 던지고 있는 것의 개선을 제안한 것은 의존 방향이 역방향이라서 개선을 제안했던 것입니다. 실무에서는 케이스에 따라 다르겠지만, 예외 2개를 처리하려고 추가로 aop를 도입하지는 않을 것 같습니다.

2023-01-19 01:34 UTC, prostars commented on src/main/java/nextstep/reservations/dto/reservation/ReservationResponseDto.java
> +    /* RestAssured에서 reflection에 사용 */
주석도 좋지만, IntelliJ가 여전히 unused로 인식하고 경고를 표시합니다.
@SuppressWarnings("unused")를 같이 사용하는 것도 좋습니다.

2023-01-19 01:34 UTC, prostars commented on src/main/java/nextstep/reservations/domain/service/reservation/proxy/ReservatioinServiceProxyHandler.java
> +    public Object invoke(final Object proxy, final Method method, final Object[] args) throws Throwable {
과하다고 생각합니다. 리플렉션은 성능도 안 좋습니다. 프록시 정리 후에 예외 처리에 대한 논의를 추가로 하는 것이 어떤가요?

2023-01-19 10:12 UTC, sgcs11 commented
service에서 예외 처리하는 코드로 원복하고 @SurpressingWarning 사용하여 unused warning 안 뜨게 했습니다!

2023-01-24 04:51 UTC, prostars commented
> service에서 예외 처리하는 코드로 원복하고 @SurpressingWarning 사용하여 unused warning 안 뜨게 했습니다!

혹시 rebase 해서 force push 하셨나요?

2023-01-25 04:38 UTC, prostars approved these changes
PR Review가 진행 중인 브랜치에 force push는 하지 말아주세요.

@SuppressWarnings("unused")를 사용한 부분에는 사용 배경을 주석으로 같이 명시해주면 좋을 것 같습니다.
@ExceptionHandler 사용하여 예외 처리 핸들러를 별도의 코드로 등록하면서, 예외를 던지는 곳과 받아서 처리하는 곳의 예외 처리 흐름이 끊겼습니다. 가능하면, 예외 처리 흐름을 보기 쉽게 하나의 흐름으로 처리하면 좋을 것 같습니다.

다음 미션도 시작한 것 같아서, 예약관리 머지하겠습니다. 고생하셨습니다.

2023-01-25 04:38 UTC, prostars commented on src/main/java/nextstep/reservations/dto/reservation/ReservationResponseDto.java
> +    @SuppressWarnings("unused")
경고를 없앤 배경 설명을 주석으로 달아주세요.

2023-01-25 04:39 UTC, merged