[jerrie.choi] roomescape Step 1&2 PR
next-step/spring-roomesacpe-reservation-kakao pull request #17
Opened 2023-01-10 13:31 UTC by CHOIJXWXN

안녕하세요 요한 ☺️
이번 미션은 코드의 완성도보다 구현하는 것이 목표였던 미션이었습니다 💦
부족함이 많은 코드겠지만 다시 한 번 리뷰 잘 부탁드립니다!

2023-01-11 10:06 UTC, leeyohan93 requested changes
안녕하세요 제리! 😄 
리뷰가 늦어져서 죄송합니다. 양해해주셔서 감사해요!
방탈출 미션을 스프링으로 개발하시느라 고생 많으셨습니다! 🙏 
레이어드 아키텍쳐에 대해 좀 더 생각해보고 개선해보면 좋을 점들이 있어서 코멘트 남겨보았어요!
궁금한 점은 언제든지 코멘트나 DM 남겨주세요~
이번 미션도 잘 부탁드립니다 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/roomescape/controller/ReservationController.java
> +    private ReservationDAO reservationDAO;
스프링에서 의존 관계를 주입할 때, 필드 주입 대신에 생성자 주입을 사용해보는건 어떨까요?
어떤 장점으로 생성자 주입을 사용하는지 알아보셔도 좋을 것 같습니다 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +public class ReservationDAO {
DAO라는 클래스 네이밍을 써주셨네요! 이러한 네이밍을 사용해주신 이유가 궁금합니다 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/roomescape/controller/ReservationController.java
> +        Reservation reservation = reservationDAO.addReservation(reservationRequest);
예약에 대한 검증은 컨트롤러 보다는 서비스 레이어를 만들어 사용해보면 어떨까요?
서비스 레이어가 있다면 중복코드를 제거하는데 많은 도움이 될 것 같아요!

구현해주신 것처럼 단순한 CRUD를 하는 케이스들에서는 별도의 레이어 없이 컨트롤러에서 처리하고 싶다는 생각이 들 수도 있는데요! 하지만 이러한 케이스는 조심스럽고 의식적으로 사용해야하며, CRUD 외에 더 많은 일을 하게 되면 애플리케이션 서비스를 만든다는 등의 명확한 가이드라인이 꼭 있어야한다고 생각합니다 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/roomescape/domain/ReservationRequest.java
> +public class ReservationRequest {
ReservationRequest 클래스를 도메인 패키지에 넣어주셨는데, ReservationRequest를 도메인 모델이라고 볼 수 있을까요?

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/resources/application.yml
> +      ddl-auto: create
이미 아실 수 있겠지만 jpa의 ddl-auto 옵션이 create일 경우 테이블을 삭제하고 다시 만들기 때문에 꼭 로컬환경에서만 사용되어야 합니다! 참고해주세요 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/nextstep/Reservation.java
> +    public Reservation(ReservationRequest reservationRequest) {
현재 Reservation -> ReservationRequest 에 대한 의존성이 존재하네요!
만약 ReservationRequest 에 변경이 일어나면 Reservation도 함께 변경해주어야 하는 상황인데요 🤔 

도메인 모델이 요청 객체에 의존하지 않도록 변경해보면 좋을 것 같습니다 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/nextstep/Reservation.java
> +
사용되지 않는 메서드는 제거해주셔도 좋을 것 같아요 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/nextstep/RoomEscapeApplication.java
> +                reservationDAO.addReservation(reservation);
웹 어플리케이션의 경우에는 `이미 예약된 경우`에 대한 검증이 있었는데 
콘솔 어플리케이션에서는 검증하지 않고 있네요!

이러한 로직도 함께 재활용 가능하도록 리팩토링해보면 좋을 것 같아요 :)

2023-01-11 10:06 UTC, leeyohan93 commented on src/test/java/roomescape/ReservationTest.java
> +public class ReservationTest {
인수테스트에 대한 부분을 잘 구현해주셨네요! 💯 💯

2023-01-11 10:06 UTC, leeyohan93 commented on src/main/java/nextstep/console/ReservationDAO.java
> +public class ReservationDAO {
현재 콘솔과 웹에서 각각 사용하고 있는 ReservationDAO 클래스는 동일한 기능을 하고 있는데요!
두 클래스에서 자바 인터페이스를 도출하여 각각의 구현체로 만들어보는건 어떨까요? 

서비스 레이어에서 이 인터페이스를 의존하게 한다면 상황에 따라 유연하게 저장하는 방법을 선택할 수 있을 것 같아요 :)

2023-01-12 01:28 UTC, CHOIJXWXN commented on src/main/java/roomescape/dao/ReservationDAO.java
> +public class ReservationDAO {
데이터베이스에 접근하는 객체여서 DAO로 이름 붙였습니다!

2023-01-12 05:20 UTC, leeyohan93 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +public class ReservationDAO {
DAO 와 Repository 패턴에 대해 고민해보시면 좋을 것 같습니다! :)

https://www.baeldung.com/java-dao-vs-repository

2023-01-12 05:50 UTC, leeyohan93 approved these changes
피드백을 잘 적용해주셨네요 👍 👍 
레이어드 아키텍처에 대해서도 고민해보신 흔적이 느껴졌습니다 👏👏
코멘트들을 남겨두었으니 다음 단계 진행하면서 함께 개선해보면 좋을 것 같아요 :)
고생하셨습니다 😄

2023-01-12 05:50 UTC, leeyohan93 commented on src/main/java/roomescape/controller/ReservationController.java
> +    private ReservationService reservationService;
final 키워드도 함께 사용해주시면 더 좋을 것 같아요 :)

```suggestion
    private final ReservationService reservationService;
```

2023-01-12 05:50 UTC, leeyohan93 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
서비스 로직에서 null을 반환하게 되면 null check의 의무가 생기고 NPE가 발생할 가능성이 생기는데요!
null 을 반환하는 대신 이미 예약이 되어있을 경우 예외를 발생시키도록 하는 것은 어떨까요?

스프링에서 예외를 처리하는 방법에 대해서도 고민해보시면 좋을 것 같습니다 :)
https://cheese10yun.github.io/spring-guide-exception/

2023-01-12 05:50 UTC, leeyohan93 commented on src/main/java/roomescape/domain/Reservation.java
> +package roomescape.domain;
적절한 도메인 모델을 찾아 패키지를 변경해주셨네요 💯 💯

2023-01-12 05:50 UTC, leeyohan93 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +    public int checkSchedule(ReservationRequest reservationRequest);
DTO 객체가 서비스 레이어를 넘어 저장소 레이어(퍼시스턴스 레이어)까지 사용되고 있네요!
만약 예약 요청 스펙이 변경되어, DTO가 변경된다면 저장소 레이어도 함께 변경해주어야 하는 상황이 생길 것 같아요.
DTO의 사용을 서비스레이어까지 제한해보는건 어떨까요?

아래 링크도 고민에 도움이 되었으면 좋겠습니다 :)
https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/

2023-01-12 05:50 UTC, leeyohan93 commented on src/main/java/nextstep/RoomEscapeApplication.java
> +    private static ReservationDAO reservationDAO = new ReservationConsoleDAO();
콘솔 어플리케이션에서도 ReservationService를 사용할 수 있도록 하여, 웹 어플리케이션과의 중복 코드를 제거해보는건 어떨까요? 😄 

```suggestion
    private ReservationService reservationService = new ReservationService(new ReservationConsoleDAO());
```

2023-01-12 05:51 UTC, merged