[kayla.park] 방탈출 예약 1,2 단계 pr 드립니다..!
next-step/spring-roomesacpe-reservation-kakao pull request #24
Opened 2023-01-11 01:36 UTC by kokomo0

안녕하세요 헨리..! 방탈출 예약 1,2단계 pr 드립니다..!!
아직 많이 부족하지만.. pr 드립니다..🥹
잘 부탁드립니다 감사합니다!

2023-01-11 07:09 UTC, topjung3 requested changes
빠른 리뷰를 위해서 핵심적인 부분만 코멘트 남겼습니다. 다른 부분은 2차 PR에서 수정해봐요~! 고생하셨습니다.

2023-01-11 07:09 UTC, topjung3 commented on src/main/java/nextstep/Reservation.java
>  public class Reservation {
현재 프로젝트 구조상으로는 domain 하위로 들어가야 할 것 같네요.

ps. 나중에 알았는데, 해당 class가 roomescape와 공유되고 있었네요. 코드 재사용적인 측면에서 좋지만 이와같은 구조를 가질 경우 보통의 상황에서는 IDE의 도움 없이는 어떤 class가 어디에서 쓰이고 있는지 확인이 어렵습니다. (ex. 코드만 리딩하는경우) 클래스를 여러패키지에서 공유하고자 할 때는 common같은 패키지를 만들어서 사용하시거나 해당 부분을 모듈화해서 빼서 사용하는게 좋아요.

현재는 두개가 아예 별개의 프로젝트 과제로 보이고 추후 어떤 리펙토링을 요구할지 모르니 분리하심이 좋아 보입니다. roomescape에 domain 패키지 아래로 Reservation가 들어가는게 좋아보이네요.

2023-01-11 07:09 UTC, topjung3 commented on src/main/java/roomescape/domain/ReservationRequest.java
> +public class ReservationRequest {
domain 아래에 있어도 사실 무방하지만 사실 ReservationRequest는 DTO에 가까운 친구니까 domain 패키지와 같은 레벨에 dto 라는 패키지(`java.roomescape.dto`)를 만들어서 옮기는게 어떨까요?

사실 ReservationRequest는 비지니스 로직과는 다른 외적인 부분 (콘솔 어플리케이션의 input) 같은 친구라 저는 따로 분리해주는게 좋더라구요.

Reservation과 Theme은 domain 혹은 model에 넣구요.

2023-01-11 07:09 UTC, topjung3 commented on src/main/java/nextstep/Reservation.java
> +    public boolean overlap(Reservation other) {
안쓰이는 것 같은 함수인데 제거하는게 어떨까요? 중복 예약을 막기 위해 만드신 것 같은데 현재 안쓰이는 함수이니 삭제하는게 좋아보입니다.

2023-01-11 07:09 UTC, topjung3 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +        Map reservationInfo = Map.of("date", reservationRequest.getDate(),
사실 이렇게 써도 문제 없는데요. Map.of 사용으로 인해서 컴파일러가 타입추론을 못하기 때문에 좌항의 Map 타입에 다이아몬드 연산자를 통해서 타입을 알려주는게 좋습니다. 
```
Map<String, ?> reservationInfo = ...
```

이러한 문제를 미리 방지하기 위해서는 intelliJ를 활용하시면 좋아요. intelliJ 가서 보시면 노란구문으로 경고가 아마 떠있을 겁니다. 이러한 문제는 경고를 확인하고 수정해주면 좋습니다. 모든 경고를 수정할 필요는 없지만 대부분의 경고는 유용합니다.

2023-01-11 07:09 UTC, topjung3 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +    public Reservation addReservation(ReservationRequest reservationRequest) {
ReservationRequest를 바로 받아서 처리하는 것 보다 Controller에서 Reservation으로 변환을 해서 주는게 어떨까요?
현재 구조상으로 보았을때 ReservationRequest는 User <-> Controller 간의 DTO라고 보시면 되고 비지니스 로직을 위한 VO, DTO 역할도 하고있는 Reservation으로 변환해서 DAO로 전달해주면 이를 저장할 때 DAO는 DB에 저장하기 위한 entity로 변환해서 저장하면 레이어간 구분이 확실해 지겠죠.

현재는 entity를 따로 만들 필요 없다고 보구요. Controller에서 ReservationRequest를 Reservation으로 변환후 DAO로 넘겨주시고 아래와 같이 작성하면 Map을 쓰는 것보다 훨씬 간결하게 insert 로직을 구현할 수 있습니다. 나중에 비지니스 로직을 위한 객체와 DB에 저장하는 entity 객체가 달라질경우 따로 만들어서 쓰면 되겠죠? (대부분의 상황에서 다릅니다.) 

```
public Reservation addReservation(Reservation reservation) {
  SqlParameterSource parameters = new BeanPropertySqlParameterSource(reservation);
  return insertActor.executeAndReturnKey(parameters).longValue();
}
```

2023-01-11 07:09 UTC, topjung3 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +    public Reservation addReservation(ReservationRequest reservationRequest) {
그리고 밑에 보면 find에서는 반환 타입이 Reservation이므로 더욱이 addReservation할 때 받는 DTO도 Reservation 인게 좋습니다.

2023-01-11 07:09 UTC, topjung3 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> new Reservation(
mapper 부분을 재사용이 가능하게 private 함수로 빼면 어떨까요?

2023-01-11 07:09 UTC, topjung3 commented on src/main/resources/application.yml
> +  jpa:
jpa 안쓰니까 제거해도 되지 않을까요?

2023-01-11 07:09 UTC, topjung3 commented on src/main/resources/application.yml
> +
소소하지만 불필요한 줄바꿈인것 같네요. 깔끔한 느낌이 들게 삭제하면 좋을 것 같습니다. 필수는 아니에요.

2023-01-11 07:27 UTC, topjung3 requested changes

2023-01-11 07:27 UTC, topjung3 commented on src/main/java/nextstep/console/ReservationDAO.java
> +        close(con);
이부분은 반드시 finally에 넣으셔야합니다. throw new RuntimeException(e); 로 unchecked exception을 던지면 프로그램이 바로 종료되므로 close 구문은 실행이 되지 않습니다. 즉 connection에 관여하는 소켓 혹은 io stream이 닫히지 않아서 누수가 발생하겠죠.

2023-01-12 08:25 UTC, topjung3 commented on src/main/java/nextstep/Reservation.java
>  public class Reservation {
확인해보다가 '콘솔 애플리케이션과 웹 애플리케이션의 중복 코드 제거해본다.' 라는 목표가 있다는 걸 공유 받아서 코멘트 추가로 남깁니다. 웹어플리케이션 항목 밑에 중복 코드 제거가 있는데 이게 이 내용인지 몰랐네요.

위의 내용은 여러가지 방법으로 개선할 수 있으나 한번 한 패키지 `roomescape` 콘솔 어플리케이션과 웹 어플리케이션을 둘다 넣는 방식으로 한번 해보면 좋을 것 같습니다.

이 작업을 하다보면 nextstep 패키지에 있는 ReservationDAO.java와 `roomescape`에 있는 ReservationDAO.java를 추상화 해야하는 목표가 생길텐데요. 메세지로 말씀드린 전략패턴을 활용하면 됩니다.

한번 이 방향으로 수정해보세요.

2023-01-13 12:49 UTC, kokomo0 commented on src/main/java/nextstep/Reservation.java
>  public class Reservation {
넵, 기존 코드에서 nextstep 패키지 하위의 코드들은 제공되는 코드였는데요, 해당 코드들을 패키지 이동을 해도 되는지 조금 혼란스러워서 그대로 두었었습니다 ㅠ,, 말씀하신대로 각 코드들의 의미에 맞게 패키지를 분리했고, dao 는 콘솔과 웹 어플리케이션에 맞게 전략패턴으로 구현해보았습니다!

2023-01-13 12:50 UTC, kokomo0 commented on src/main/java/roomescape/domain/ReservationRequest.java
> +public class ReservationRequest {
네, dto 패키지 하위에 넣었고, 이름도 ReservaionDto로 변경하였습니다!

2023-01-13 12:51 UTC, kokomo0 commented on src/main/java/nextstep/Reservation.java
> +    public boolean overlap(Reservation other) {
넵, 사용하지 않는 함수 맞고 제거하였습니다!

2023-01-13 13:25 UTC, kokomo0 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +        Map reservationInfo = Map.of("date", reservationRequest.getDate(),
아하.. 확실히 경고에서 떴었는데 다 확인을 하지 않고 커밋을 하였습니다 ㅠㅠ.. 잘 확인해보도록 하겠습니다!  중요한 문제인데 자세히 봐주셔서 감사합니다..!

2023-01-13 13:26 UTC, kokomo0 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +        Map reservationInfo = Map.of("date", reservationRequest.getDate(),
? 타입을 이런데 사용할 수 있네요..!

2023-01-13 13:33 UTC, kokomo0 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +    public Reservation addReservation(ReservationRequest reservationRequest) {
헨리가 말씀해주신 덕분에 구조에 대해 조금 가닥이 잡힌 것 같습니다 ㅠㅠ!! 네, ReservationRequest는 이름 그대로 사용자가 입력하는 형식을 받기 위한 클래스인데요, User<->Controller 간의 DTO라고 말씀해주셔서 좀더 명확하게 생각이 되는것 같습니다..! 컨트롤러에서 DTO를 받아서 Reservation으로 변환한 뒤 DAO로 넘겨주도록 수정하였습니다.
알려주신 코드도 꿀팁이네요..! 훨씬 코드가 간결해졌습니다 감사합니다!!

2023-01-13 13:37 UTC, kokomo0 commented on src/main/java/roomescape/dao/ReservationDAO.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> new Reservation(
넵, mapper에 대해 검색해보니 RowMapper의 mapRow라는 함수를 사용하고 있어서 해당 클래스를 상속받는 클래스를 만들어서 빼주었습니다! 쿼리문은 전략패턴의 인터페이스로 옮겼습니다!
좋은 조언 감사드립니다!!

2023-01-13 13:40 UTC, kokomo0 commented on src/main/resources/application.yml
> +  jpa:
넵.. 될때까지 이것저것 시도해본 결과물입니다. application.yml의 내용에 적힌 것들은 정확하게 파악하고 사용한 것이 아닙니다. (코드가 돌아가니 더 수정하지 않고 그냥 두었습니다..) 부끄럽네요.. 좀 더 공부하도록 하겠습니다..😢

2023-01-13 13:41 UTC, kokomo0 commented on src/main/resources/application.yml
> +
넵 줄바꿈도 수정했습니다!

2023-01-13 13:42 UTC, kokomo0 commented on src/main/java/nextstep/console/ReservationDAO.java
> +        close(con);
아하..!! 중요한 부분인데 놓치고 있었습니다! 알려주셔서 정말 감사드립니다!

2023-01-16 02:27 UTC, topjung3 approved these changes
대부분의 내용이 수정 되었고, 3차 미션도 있으셔서 3차 PR 좀 더 같이 봐요. 고생하셨습니다.

그리고 interface에서 query문을 변수로 넣어두셨는데 사실 지금 상황에서는 문제 없지만 미래에 확장을 위해서 mongo나 redis 같은 다른 db 를 사용하게 되면 저 query는 불필요한 친구가 될 수 있겠죠. 이럴경우 중간에 abstract class를 하나 두는 것도 좋습니다. `ReservactionDao - AbstractReservationMysqlDao - ReservationDaoWeb, ReservactionDaoConsole`

추가로 지금은 적용할 내용이거나 필수적인 부분은 아닌데, DAO와 Repository에 차이점에 대해서 아시면 좋아서 링크 하나 드립니다.
https://bperhaps.tistory.com/entry/Repository%EC%99%80-Dao%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90

고생하셨습니다~

2023-01-16 02:27 UTC, merged

2023-01-16 18:22 UTC, topjung3 commented on src/main/java/roomescape/domain/ReservationRequest.java
> +public class ReservationRequest {
헉 이름은 매우 잘 지으셨다고 생각했었는데 ㅎㅎ 고생하셨습니다~!