Spring Basic - 예약 관리
next-step/spring-roomesacpe-reservation-kakao pull request #36
Opened 2023-01-11 06:01 UTC by Nelfunction

2023-01-11 07:00 UTC, sehan commented
PR 요청시에는 해당 step 의 branch 를 생성 후 PR 요청해주세요.  그렇지 않으면 다음 step 에서 이전 step 코드의 commit 들이 모두 포함되어 올라오기 때문에 리뷰가 어려워 집니다.

2023-01-11 07:43 UTC, sehan requested changes
안녕하세요. eugene 돌아왔군요. 환영합니다. 😊 

레이어드 아키텍쳐 기반으로 패키지 분리는 잘 되어 있지만 도메인이 web layer 까지 의존을 가지고 있습니다.
개선을 통해 이 의존을 제거해보면 좋겠습니다. 

추가적인 개선사항들은 코드에 코멘트로 남겨두었습니다. 
확인 후 개선 요청드립니다.

2023-01-11 07:43 UTC, sehan commented on src/main/java/nextstep/controller/ReservationController.java
> +    public ResponseEntity createReservation(@RequestBody Reservation reservation){
api 파라미터를 받는 클래스로 Reservation 을 그대로 사용하게 되면 사용자입력대한 변경이 필요할 경우 Reservation 를 수정해야 합니다. Reservation 은 도메인에 해당하는 클래스이기 때문에 사용자입력 변경에 영향을 받지 않는것이 좋습니다.  그래서 사용자입력을 받는 클래스를 별도로 생성해서 사용하는것이 좋습니다.  
 현재 상태라면 사용자가 예약id 도 파라미터로 넘길수 있는 상태입니다.

2023-01-11 07:43 UTC, sehan commented on src/main/java/nextstep/service/ReservationService.java
> +        }
모든예약을 비교하여 중복예약여부를 확인할 수도 있겠지만 해당시간에 예약이 존재하지는 여부를 repository 에게 요청하면 더 좋지 않을까요?

2023-01-11 07:43 UTC, sehan commented on src/main/java/nextstep/repository/ReservationConnRepository.java
> +        conn = DriverManager.getConnection("jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=true", "sa", "");
connection 은 runtime 시 즉, 사용시 생성을 해서 사용을 다 한 후에는 반환을 시키는 형태로 사용해야 합니다. 
close 하는 코드 샘플들을 참고해보세요
https://www.tabnine.com/code/java/methods/java.sql.Connection/close

2023-01-11 07:43 UTC, sehan commented on src/main/java/nextstep/dto/Reservation.java
> +public class Reservation {
Reservation 과 Theme 의 경우 예약관리 어플리케이션에서 중요한 도메인 객체로 볼 수 있습니다.
코드전반에 DTO 성격으로 사용하고 있는데 해당 객체를 도메인객체로 분류하고 view 로 전달할때는 불변객체에 담아서 전달하는 방식이 좋습니다.  

앞서 Controller 에서 Reservation 을 파라미터에 직접 사용한 부분과 연관되는 내용입니다. 
파라미터에 직접사용함으로 인해 발생한 view 의존을 제거해주세요

2023-01-12 07:20 UTC, Nelfunction commented
step2 브랜치를 새로 생성한 뒤 새 PR을 생성했습니다. #52 
스프링에서의 도메인 모델, DTO, Entity에 관하여 간단한 설명도 곁들여 주시면 감사하겠습니다. 🙂

2023-01-12 07:20 UTC, closed without merging