[jacob.hyeon] 방탈출 예약관리 - 1단계 & 2단계
next-step/spring-roomesacpe-reservation-kakao pull request #5
Opened 2023-01-10 08:27 UTC by kjaehyeon

[프로그래밍 요구사항]
- 기존 콘솔 애플리케이션은 그대로 잘 동작해야한다.
- 콘솔 애플리케이션과 웹 애플리케이션에서 각각 데이터베이스에 접근하는 로직을 구현한다.
- 콘솔 애플리케이션에서 데이터베이스에 접근 시 JdbcTemplate를 사용하지 않는다. 직접 Connection을 생성하여 데이터베이스에 접근한다.
- 웹 애플리케이션에서 데이터베이스 접근 시 JdbcTemplate를 사용한다.
- 콘솔 애플리케이션과 웹 애플리케이션의 중복 코드 제거해본다.

2023-01-11 07:48 UTC, devk0ng requested changes
수고하셨습니다 제이콥~!
코드에서 스프링으로 개발을 많이 하셨다는게 느껴질만큼 잘 구현해주신 것 같습니다 :)
간단한 코멘트들 몇가지 남겼습니다.
확인 부탁드리며 반대 의견이나 궁금한 사항은 언제든지 편하게 말씀주세요~

2023-01-11 07:48 UTC, devk0ng commented on src/main/java/nextstep/RoomEscapeApplication.java
> +            System.out.println("- 종료: quit");
해당 파일 내에 리뷰할 내용들이 보이는데 커밋 이력을 보니 해당 파일은 제공받은 것이고 리뷰 대상이 아니라고 생각하면 될까요??

2023-01-11 07:48 UTC, devk0ng commented on src/main/java/roomescape/controller/RoomReservationController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
ResponseEntity.created()를 사용하는 것은 어떨까요?? (파라미터로는 Location 헤더에 들어갈 내용을 넘겨줍니다)
```
If one or more resources has been created on the origin server as a
   result of successfully processing a POST request, the origin server
   SHOULD send a 201 (Created) response containing a Location header
   field that provides an identifier for the primary resource created
   ([Section 7.1.2](https://www.rfc-editor.org/rfc/rfc7231#section-7.1.2)) and a representation that describes the status of the
   request while referring to the new resource(s).
```
[rfc 문서](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.3)에서 post 부분을 가져온 내용입니다.
post 메소드의 결과로는 생성된 리소스를 가리키는 정보가 Location 헤더에 담겨 넘어가게 하는 것이 좋습니다. 이는 Restful한 디자인과도 관련이 있을 것 같습니다. 
공부하는 느낌으로 한번 적용해보시는 건 어떨까용??

2023-01-11 07:48 UTC, devk0ng commented on src/main/java/roomescape/repository/ReservationRepository.java
> +public interface ReservationRepository {
interface로 잘 정의해주신 것 같습니다!
다만 한가지 코멘트를 남기자면 만약 추가 요구사항으로 인해 다른 Repository를(ex. UserRepository) 구현해야할 상황을 가정해본다면 ReservationRepository와 동일하게 생긴 인터페이스가 추가되는 방향으로 아마 가지 않을까 생각합니다.
현재 interface의 추상메소드를 보면 결국 가장 기본적인 crud에 해당하는 내용들이며 이는 위의 예처럼 다른 Repository들에도 동일하게 적용되는 내용입니다.
[Spring Data Repsoitory 내의 인터페이스들](https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html)을 참고하여 이 부분을 조금 더 고민해보는 것은 어떨까요??

2023-01-11 07:48 UTC, devk0ng commented on src/main/java/roomescape/repository/ReservationWebRepository.java
> +public class ReservationWebRepository implements ReservationRepository {
현재 Repository 내의 내용을 확인했을 때에는 DAO에 조금 더 가까운 내용들로 개인적으로는 생각됩니다. 
[해당 문서](https://www.baeldung.com/java-dao-vs-repository)를 참고하여 고민 한번 부탁드립니닷~!

2023-01-11 07:48 UTC, devk0ng commented on src/main/java/roomescape/repository/ReservationConsoleRepository.java
> +    private final String DB_PASSWORD = "";
기존에 메소드 내에 단순 문자열로 들어가있던 것을 상수화 시켜준 것은 좋은 판단이었던 것 같습니다!
한가지 더 말씀드리자면 데이터베이스 접속 정보와 같은 데이터들은 application.yml 혹은 application.properties 파일에 정의를 한 후 사용하는 것은 어떨까요??
해당 위치로 옮길경우에 얻게되는 이점은 코드에 노출이 되기에 민감한 정보에 대해 다양한 솔루션 적용을 검토해볼 수 있으며 config server와 같은 구조를 가져갈수도 있을 것 같습니다. 
(현재 저희셀에서는 [vault](https://www.vaultproject.io/)를 사용하여 민감한 접속 정보들을 관리하고 있습니다)

2023-01-11 07:48 UTC, devk0ng commented on src/main/java/roomescape/dto/ReservationResponse.java
> +        return new ReservationResponse(
요 내용은 꼭 반영하실 필요는 없습니다!
mapper 기능을 제공하는 라이브러리를 이용하면 이런 객체간의 변환 코드를 조금 더 효율적으로 관리할 수 있습니다.
(개인적으로는 [mapstruct mapper](https://mapstruct.org/)가 편리한 것 같습니다)

2023-01-11 08:20 UTC, kjaehyeon commented on src/main/java/nextstep/RoomEscapeApplication.java
> +            System.out.println("- 종료: quit");
넵 이 부분은 제공받은 것이라서 리뷰 대상 아니라고 생각하시면 될 것 같습니다!

2023-01-11 08:22 UTC, kjaehyeon commented on src/main/java/roomescape/repository/ReservationConsoleRepository.java
> +    private final String DB_PASSWORD = "";
- 넵 접속 정보는 따로 관리하도록 변경하겠습니다!
- ReserationConsoleRepository에는 try with resource 문을 적용했는데 혹시 잘못 적용한 것 일까요??

2023-01-12 01:09 UTC, devk0ng commented on src/main/java/roomescape/repository/ReservationConsoleRepository.java
> +    private final String DB_PASSWORD = "";
아이고 저 뒤에 내용은 마지막에 급하게 보고 추가한 내용인데 제가 잘 못 봤습니다 ㅠㅠ
혼란을 드렸네용.. 무시해주시고 진행하시면 될 것 같습니다!

2023-01-12 09:16 UTC, devk0ng approved these changes
LGTM~! 👍

2023-01-12 09:16 UTC, merged