[omin.ju] 방탈출 예약 1,2step 입니다!
next-step/spring-roomesacpe-reservation-kakao pull request #55
Opened 2023-01-12 07:50 UTC by HONGMINJU

안녕하세요!
방탈출 예약 1,2step 입니다!

2023-01-13 00:52 UTC, JisooJang requested changes
오민 안녕하세요,
혹시 이번 PR은 1,2단계가 같이 한꺼번에 리뷰된 이유가 있을까요?

그리고 이번 PR은 설명에 클래스간 관계설명이나 PR 목적에 대한 서술이 한개도 없어서 
이렇게 많이 변경된 코드를 보는데 리뷰하는 입장에서 조금 파악하는데 시간이 걸렸네요.

저번처럼 클래스 다이어그램까진 아니더라도,
PR에 구체적인 PR에 대한 설명을 적어주셨음 합니다.

1단계진행의 경우 리뷰어들에게 일단 머지하고, 피드백내용을 다음단계에서 수정하라고 권장하고있는데요,
본 PR은 2단계까지 포함되어있는것 같아서 일단 머지하지 않고 피드백만 남기겠습니다.

남겨드린 내용 확인부탁드려요!

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/controller/ReservationController.java
> +        if(reservationDetail == null){
if문이나 try catch문 사용하실때 전반적으로 코딩 컨벤션을 지켜주시는게 좋을것 같아요.
구글링해보시면 java 코딩 컨벤션에 대한 자료가 많이 나옵니다.

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/dao/DatabaseUtil.java
> +    private static final String PASSWORD = "root";
데이터베이스 연결 정보는 별도의 property(yaml) 파일로 저장되어 관리하고, 
필요한 컴포넌트에서 @Value로 주입받아 사용받는 방식을 주로 현업에서 사용합니다.

일반적으로 현업에서는 환경별로 각각 다른 연결 정보를 가지는데,
설정정보에 이를 환경별로 저장해서 관리 할수 있고,
우리는 앱을 구동시킬때 실행시키고자하는 프로파일만 넘겨주시면,
 해당 프로파일에 맞는 설정정보가 주입되는 과정입니다.

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/dao/DatabaseUtil.java
> +            }catch (Exception exception){
이쪽도 java 코딩컨벤션을 같이 확인해주시면 좋을 듯 합니다.

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/dao/DirectConnectionThemeDao.java
> +    private static List<Theme> getTheme(Long id, ResultSet resultSet) throws SQLException {
이 메서드가 static으로 선언된 이유가 무엇일까요?
그리고 DAO 클래스의 책임은 어디까지일지 고민해보셔도 좋을것 같습니다.

*
현업에서는 엔티티를 response 객체로 변환하거나, 반대로 request 객체를 엔티티로 변환할때
Mapper라는 컴포넌트를 별도 만들어서 데이터 변환에 대한 책임을 분리하고 있습니다.]
참고하시면 좋을것 같아요

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/dao/DirectConnectionThemeReservationDao.java
> +    private static List<Reservation> getReservation(Long id, ResultSet resultSet) throws SQLException {
이 부분도 위에 DirectConnectionThemeDao 클래스에서 피드백드린 내용과
비슷한 방향으로 고민해보셔도 좋을것 같아요

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/dao/ThemeReservationDao.java
> +@Repository
이쪽에 Repository 어노테이션이 붙은건 혹시 의도하신 내용일까요?

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/domain/Reservations.java
> +public class Reservations {
제가 코드를 확인했을땐 이 클래스가 참조되는곳이 없는것 같은데, 
어떨때 활용되는 클래스일까요? getInstance() 메서드나 등등 호출되는곳이 없어보여서 궁금합니다.

2023-01-13 00:52 UTC, JisooJang commented on src/main/java/nextstep/domain/Themes.java
> +public class Themes {
이클래스도 호출되는곳을 찾기가 어려운데, 어떨때 쓰이는 용도인지 궁금합니다.

2023-01-13 06:13 UTC, HONGMINJU commented on src/main/java/nextstep/domain/Reservations.java
> +public class Reservations {
Step1 과제에서 사용한 클래스입니다!
DB연결없이 방탈출 예약 시스템을 구현하는 것이 step1이었습니다.
제가 너무 급히 PR을 날리다 보니 과제나 클래스에 대한 설명이 없었습니다!!
다음 과제부터 자세한 설명을 첨부하겠습니다!!

2023-01-13 06:14 UTC, HONGMINJU commented on src/main/java/nextstep/domain/Themes.java
> +public class Themes {
Reservations클래스와 동일하게 Step1에서 사용한 클래스입니다!

2023-01-13 06:21 UTC, HONGMINJU commented
이번주 과제는 step은 3가지로 나뉘어져 있지만 PR은 step1,2와 step3으로 나눠서 진행하라고 하셔서 1,2를 합쳐 PR을 올리게 되었습니다!

- step1 : 방탈출예약 시스템을 DB연결 없이 콘솔 애플리케이션, 웹 애플리케이션으로 구현
- step2 : step1에서 구현한 내용을 DB와 연결 
  (콘솔 애플리케이션은 직접 커넥션을 만들어서 DB와 연결, 웹 애플리케이션은 JdbcTemplate을 이용하여 DB와 연결)
- step3 : 테마 생성, 조회, 수정, 삭제 API 만들기

2023-01-13 08:13 UTC, HONGMINJU commented on src/main/java/nextstep/dao/DatabaseUtil.java
> +            }catch (Exception exception){
수정해서 다시 올렸습니다!!

2023-01-13 08:14 UTC, HONGMINJU commented on src/main/java/nextstep/controller/ReservationController.java
> +        if(reservationDetail == null){
수정해서 다시 올렸습니다!!

- if, catch, 함수 선언 시 띄어쓰기 추가
- 클래스 시작 시 빈 줄 추가

진행했습니다!

2023-01-16 01:56 UTC, HONGMINJU commented on src/main/java/nextstep/dao/DatabaseUtil.java
> +    private static final String PASSWORD = "root";
말씀주신 대로 `@Value`를 이용해서 데이터베이스 정보를 주입받도록 수정했습니다.
이렇게 하니 소스코드 상에서 데이터베이스 정보가 들어나지 않아 좋은 것 같습니다!!

2023-01-19 07:08 UTC, HONGMINJU commented on src/main/java/nextstep/dao/ThemeReservationDao.java
> +@Repository
아니요!! 잘못들어간 것 같아 삭제했습니다!

2023-01-19 07:10 UTC, HONGMINJU commented on src/main/java/nextstep/dao/DirectConnectionThemeDao.java
> +    private static List<Theme> getTheme(Long id, ResultSet resultSet) throws SQLException {
step3에서는 mapper를 이용해보겠습니다!

2023-01-19 07:11 UTC, HONGMINJU commented on src/main/java/nextstep/dao/DirectConnectionThemeReservationDao.java
> +    private static List<Reservation> getReservation(Long id, ResultSet resultSet) throws SQLException {
불필요한 static 제거했습니다!

2023-01-19 13:39 UTC, merged