[veurs.j] 3단계 구현
next-step/spring-roomesacpe-reservation-kakao pull request #77
Opened 2023-01-13 08:41 UTC by wilgur513

기능 구현에 집중해서 우선 PR 올립니다. 아직 레포지토리에 대한 테스트를 작성하지 않았는데, 보내주실 피드백 반영과 함께 작성하겠습니다~

2023-01-16 03:21 UTC, parksjin01 requested changes
3단계 코드도 요구사항에 맞게 잘 작성해주신 것 같아요 👍 
코드를 보며 추가로 고려되면 좋을 것 같은 내용들을 코멘트로 남겨두었습니다

레포지토리에 대한 테스트를 추가해주실 때, 컨트롤러에서 에러 응답을 처리하는 부분에 대한 테스트 코드도 함께 추가되면 좋을 것 같아요.
3단계 미션에서 요구사항이 추가된 것 같은데요, README 파일도 함께 업데이트 부탁드릴게요 😄

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/console/RoomEscapeApplication.java
> +        createDataBaseTables(dataSource);
매번 DB 커넥션을 생성하는 대신 DBCP를 적용해주셨네요 👍

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/console/RoomEscapeApplication.java
> +        config.setPassword("");
콘솔 어플리케이션에서도 `test` 대신 `prod` 데이터베이스를 사용해보는 것은 어떨까요?

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/console/RoomEscapeApplication.java
> +        config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
스프링을 사용할 때와 HikariCP 설정이 다른것 같은데요, 혹시 의도하신 부분일지 궁금합니다

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/model/Theme.java
>      private Integer price;
모델 역할을 하는 클래스의 멤버 변수가 변경되지 않는다면 `final`을 추가해보는 것은 어떨까요?

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/repository/JdbcReservationRepository.java
> +            throw new IllegalStateException(e);
`SQLException`을 런타임 예외인 IllegalStateException으로 레핑해서 전달하도록 수정해주셨네요 👍 

지금은 `System.out.println`과 `System.err.println`으로 로그 메시지를 출력하고 있는 것 같은데요,
로거를 사용해서 로그 메시지를 출력해보는 것도 좋을것 같아요 😄

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/service/RoomEscapeService.java
>      }
예약을 추가할 때 항상 고정된 테마 예약만 가능한것 같은데요,
3단계 요구사항으로 신규 테마 생성, 삭제 기능이 추가되었으니, 
예약을 할 때에도 DB에 저장된 테마를 선택할 수 있도록 해보는 것은 어떨까요?

---

아래는 코드에 영역을 지정해서 코멘트를 추가할 수 없어서 해당 코멘트에 함께 남겨둡니다.
`RoomEscapeService`에서 발생하는 Exception에 맞는 에러응답을 전달하는 로직이 컨트롤러에 추가해보는 것은 어떨까요?
지금은 에러 발생시 **Internal Server Error** 가 에러 응답으로 전달되고 있어서요

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/web/dto/ThemeRequest.java
> +    private final int price;
테마 요청, 응답의 DTO 역할을 하는 클래스 멤버 변수를 `final`로 지정해주셨네요 👍 
예약 요청, 응답의 DTO 역할을 하는 클래스 멤버 변수도 `final`로 지정해주시면 좋을것 같아요

2023-01-16 03:21 UTC, parksjin01 commented on src/main/java/nextstep/web/RoomEscapeApplication.java
> +    }
레포지토리와 서비스 빈을 직접 등록해주셨네요.
아마 `web.RoomEscapeApplication` 클래스가 포함된 패키지의 외부에 클래스가 있어서 어노테이션을 붙여도 빈 등록이 되지 않아서
직접 빈을 등록해주셨다고 추측해봤는데요. (혹시 아니라면 말씀해주세요 😅 )

`@SpringBootApplication`이 붙어있는 클래스의  패키지 외부에 있는 클래스를 빈으로 등록할 때 
지금처럼 빈을 직접 등록해주는 것도 좋은 방법인것 같은데요, 추가로 고려해볼 수 있는 방법도 남겨봅니다.

- `@SpringBootApplication`에 `scanBasePackages` 파라미터를 전달해서 컴포넌트 스캔을 시작하는 패키지 위치 변경
- `RoomEscapeApplication` 클래스를 `web` 패키지 외부의 `nextstep` 하위로 이동
   (패키지 이동시, 콘솔용 `RoomEscapeApplication` 위치도 변경하고, 클래스 이름으로 웹, 콘솔 구분을 해볼수 있을것 같아요)

2023-01-16 03:21 UTC, parksjin01 commented on src/main/resources/schema.sql
> +    primary key (id)
테마 정보를 저장하는 테이블이 추가되면서, `RESERVATION` 테이블의 
`theme_name`, `theme_desc`, `theme_price` 컬럼과 중복되는 부분이 있는 것 같은데요.
DB에 데이터가 중복해서 저장되는 부분을 제거해보는 것은 어떨까요?

2023-01-16 03:21 UTC, parksjin01 commented on src/test/java/nextstep/web/ThemeControllerTest.java
> +
테마 생성, 삭제 기능이 추가됨에 따라서 테마 컨트롤러에 대한 테스트 코드를 추가해주셨네요 👍 
컨트롤러와 함께 테마 서비스 클래스도 추가되어서 서비스 클래스에 대한 테스트 코드도 추가해보는 것은 어떨까요?

2023-01-16 06:07 UTC, wilgur513 commented on src/main/java/nextstep/console/RoomEscapeApplication.java
> +        config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
아... 이거 Hikaricp 예제보고 가져오다 보니... 특별한 생각없이 가져왔습니다 ㅠㅠ
직접 pool을 생성하는 게 처음이다 보니, 어떤 설정이 정확히 필요한지 몰라서... 제공되는 예제대로 사용했습니다.
보니깐 특별한 설정을 하지 않으면 기본 설정으로 동작하는 것 같아 해당 코드는 제거했습니다~

2023-01-16 10:52 UTC, parksjin01 requested changes
코멘트 드렸던 내용들을 빠르게 적용해주셨네요 👍 
수정해주신 코드를 바탕으로 몇가지 추가 코멘트를 남겨뒀는데요,
코멘트를 적용해주셔도 좋고, 다음 단계 미션을 진행하시면서 참고해주셔도 좋을것 같아요.
(코멘트 중 참고해서 다음 단계를 진행하고자 하는 부분들은 베루스의 의견을 짧게 남겨주셔도 좋을것 같아요)

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/console/RoomEscapeApplication.java
>          System.out.println("### 명령어를 입력하세요. ###");
콘솔용 `RoomEscapeApplication`의 경우 MVC 패턴을 따르고 있지 않은것 같은데요,
MVC 패턴에 맞게 클래스를 분리해보는 것도 좋을것 같아요.
(이번 미션에서는 진행하지 않으셔도 되고, 참고만 해주시면 좋을것 같아요)

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/repository/ConsoleReservationRepository.java
> +
클래스의 이름을 레포지토리를 사용하는 클라이언트 클래스를 나타내도록 변경해주셨네요.
변경해주신 이름을 보면 어떤 클래스가 해당 레포지토리를 사용할지 빠르게 파악할 수 있어 좋은것 같아요

저는 개인적으로는 변경전 이름을 선호하는데요. 
변경전 클래스 이름을 보면 레포지토리 클래스가 `JdbcTemplate` 사용하는지 알 수 있고,
요구사항이 변경되어 웹에서 `JdbcTemplate`을 사용하지 않는 레포지토리를 호출해도 어색하지 않을것 같아요.

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/repository/ConsoleReservationRepository.java
> +        this.logger = LoggerFactory.getLogger(ConsoleReservationRepository.class);
로거는 static 변수로도 많이 사용하는데요, 생성자 대신 static 변수로 정의하면서 함께 초기화 시켜보는 것은 어떨까요?

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/repository/ConsoleReservationRepository.java
> +                        new Theme(themeName, themeDesc, themePrice));
위 코드가 `WebReservationRepository`의 ROW_MAPPER와 중복되는 부분이 있는것 같은데요.
중복을 제거할 수 있는 방법이 있을까요?

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/repository/ConsoleThemeRepository.java
> +    private long id;
콘솔용 레포지토리에서 DB 사용 대신 `Map`으로 데이터를 저장하신 이유가 궁금합니다.

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/repository/ReservationConverter.java
> -    }
`get` 메소드를 삭제하고 `RowMapper`를 사용하셨네요 👍 
`PreparedStatement`에 파라미터를 설정하기 위해서 사용하는 `PreparedStatementSetter`도 참고해보시면 좋을것 같아요

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/web/ControllerAdvice.java
> +    }
서비스에서 에러 발생시 에러 응답이 전달되도록 `@RestControllerAdvice`를 추가해주셨네요 👍 
지금은 에러 메시지가 바로 전달되고 있는데요, 에러 응답도 JSON 포멧으로 전달해주는 것도 좋을것 같아요.

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/web/ControllerAdvice.java
> +public class ControllerAdvice {
현재는 일부 예외 발생시에만 에러 처리가 되고, 다른 예외들은 기본 에러 응답이 전달되는데요,  
다른 예외 발생시에도 항상 서비스에서 정의한 일반적인 에러문구를 전달해보는 것은 어떨까요?

동일한 `internal server errror` 메시지가 전달되더라도, 기본 에러 응답이 사용자에게 전달되는 것보다는 
서비스에서 정의한 에러 응답이 내려가는 것이 좋을 것 같아요

2023-01-16 10:52 UTC, parksjin01 commented on src/main/java/nextstep/web/ThemeController.java
> +    }
사용자가 전달한 값을 검증하는 로직을 추가하는 것은 어떨까요?

현재는 테마의 `price` 값에 음수를 넣어도 정상 동작하고, 
사용자가 `name`이나 `desc`을 길게 입력하는 경우 DB 에러가 발생하는데요.

사용자가 전달한 값을 체크해서 음수를 입력하지 못하게 하거나, 
사용자가 입력한 값의 길이가 유효하지 않으면 DB 요청을 하지 않고 에러처리를 할 수도 있을 것 같아요

2023-01-16 10:52 UTC, parksjin01 commented on src/test/java/nextstep/web/RoomEscapeControllerTest.java
> +public class RoomEscapeControllerTest extends AbstractControllerTest {
에러 응답에 대한 테스트가 추가해보는 것은 어떨까요?
동일한 예약을 생성하려고 하거나, 없는 예약 정보를 조회하려고 할 때 적절한 에러처리가 되는지도 테스트되면 좋을것 같아요.

레포지토리 클래스들에 대한 테스트 코드도 별도로 작성되면 좋을것 같아요.
이미 컨트롤러나 서비스의 테스트 코드를 통해서 테스트가 되기는 하지만, 레포지토리의 동작만 확인하는 테스트 코드가 있으면
레포지토리 코드 수정으로 인한 테스트 실패시, 원인을 파악하는데 도움이 될것 같아요.

2023-01-19 06:42 UTC, wilgur513 commented on src/main/java/nextstep/repository/ConsoleThemeRepository.java
> +    private long id;
콘솔용 애플리케이션에서 DB에 Theme 테이블을 추가하기에는 시간적 여유가 없다고 느껴져서... 급하게 하느라 우선 Map으로 했습니다.

2023-01-19 07:10 UTC, wilgur513 commented on src/main/java/nextstep/console/RoomEscapeApplication.java
>          System.out.println("### 명령어를 입력하세요. ###");
MVC 분리는 시간 상 못할꺼 같습니다 ㅠㅠ

2023-01-19 07:10 UTC, wilgur513 commented on src/main/java/nextstep/repository/ConsoleReservationRepository.java
> +        this.logger = LoggerFactory.getLogger(ConsoleReservationRepository.class);
변경했습니다

2023-01-19 07:10 UTC, wilgur513 commented on src/main/java/nextstep/repository/ConsoleReservationRepository.java
> +                        new Theme(themeName, themeDesc, themePrice));
RowMapper 클래스를 따로 분리했습니다~

2023-01-19 07:10 UTC, wilgur513 commented on src/main/java/nextstep/web/ControllerAdvice.java
> +    }
ErrorResponse 추가 했습니다

2023-01-19 07:10 UTC, wilgur513 commented on src/main/java/nextstep/web/ControllerAdvice.java
> +public class ControllerAdvice {
변경했습니다

2023-01-19 07:11 UTC, wilgur513 commented on src/main/java/nextstep/web/ThemeController.java
> +    }
Validator 사용해서 검증 추가했습니다

2023-01-19 07:11 UTC, wilgur513 commented on src/test/java/nextstep/web/RoomEscapeControllerTest.java
> +public class RoomEscapeControllerTest extends AbstractControllerTest {
에러 응답 테스트 추가했습니다. 레포지토리 테스트는 시간이 부족해서 ㅠㅠ 다음에 기회가 있다면 하겠습니다...

2023-01-25 01:58 UTC, parksjin01 commented on src/main/java/nextstep/repository/ConsoleReservationRepository.java
> +                        new Theme(themeName, themeDesc, themePrice));
RowMapper를 별도 클래스로 분리해서 JdbcTemplate 사용 유무와 관련없이 
조회한 데이터를 객체로 만드는 부분의 중복코드가 제거되었네요 👍

2023-01-25 02:02 UTC, parksjin01 commented on src/main/java/nextstep/web/ControllerAdvice.java
> +    }
ErrorResponse를 사용해서 에러 응답도 JSON 포멧으로 전달되네요 👍 
이후 에러 응답별로 에러 코드나 다른 정보가 추가되는 경우에는 ErrorResponse 클래스에 변수를 추가해서 JSON 필드 추가가 가능하고
API를 호출하는 클라이언트는 JSON 응답을 파싱해서 필요한 정보를 가져갈 수 있을것 같아요

2023-01-25 02:10 UTC, parksjin01 commented on src/main/java/nextstep/web/ThemeController.java
> +    }
`@Valid` 어노테이션과 `@Min`, `@Max`, `@NotBlank` 등의 어노테이션을 사용해서 사용자 입력값을 검증하셨네요 👍 

지금은 테마 이름을 검증할 때 최대 길이를 255로 체크하고 있는데, 
DB의 최대 길이는 20자라서 DB 최대 길이에 맞춰주시면 좋을것 같아요.

지금은 Validator 체크에서 에러 발생시 아래 에러 메시지가 전달되는데요,
사용자가 에러 원인을 파악하기 좋게 에러 메시지를 변경하는 방법을 고민해보셔도 좋을것 같아요 😄 

```
{
    "message": "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Void> nextstep.web.ThemeController.createTheme(nextstep.web.dto.ThemeRequest): [Field error in object 'themeRequest' on field 'price': rejected value [-1]; codes [Min.themeRequest.price,Min.price,Min.int,Min]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [themeRequest.price,price]; arguments []; default message [price],0]; default message [0 이상이어야 합니다]] "
}
```

2023-01-25 02:15 UTC, parksjin01 approved these changes
안녕하세요 베루스~ 설 연휴 잘 보내셨나요?
설 연휴로 PR 리뷰가 늦어졌네요.

리뷰 요청 주신 코드중 Validator를 사용하는 부분과 관련해서 간단한 코멘트를 남겨두었는데요,
다음 미션들 진행시 참고해주시면 좋을것 같아요.
(코멘트는 이전 리뷰 코멘트의 댓글로 남겨 두었습니다.)

3번째 미션 진행하시느라 고생하셨습니다. 이번 미션 PR 머지할게요 😄

2023-01-25 02:16 UTC, merged