[herbi.sf8] 방탈출 예약 관리 step3
next-step/spring-roomesacpe-reservation-kakao pull request #84
Opened 2023-01-15 12:09 UTC by herbi1411

안녕하세요! 제출이 늦었습니다. 이번 미션은 테마를 예약 테이블에서 분리, 테마 관리 기능 콘솔에 추가, 테마 관리 API 생성 이렇게 3가지 작업이 있었습니다. 작업하며 추가된 내용(API 명세, 파일 구조)는 README에 업데이트 했습니다!

저번에 피드백 주신대로 이번에는 커밋을 기능별로 더 많이 해보려고 노력했습니다! 커밋 메시지에도 제가 한 작업을 적었는데 다시한번 기술해보겠습니다.

- lombok 라이브러리 적용
    - 도메인 객체 생성에 필요한 인자값이 많은 것 같아서 롬복 라이브러리를 사용해 빌드패턴을 적용해봤습니다. 코드를 직접 작성할 수도 있지만 getter, equals등 메서드를 어노테이션으로 간단히 만들 수 있어서 좋았던 것 같습니다. 다만 빌드패턴을 사용하니 객체 생성할 때 어떤 값을 넣는 지는 명확해졌는데 코드 길이가 더 길어져서 파일이 깔끔해지지 않는 단점이 있는 것 같다고 느꼈습니다.
- Service에 Transactional 어노테이션 붙이기
    - 서비스 클래스에는 Transactional을 붙여서 서비스의 각 일련의 작업을 트랜잭션으로 만들었습니다. DB의 조회만 필요한 작업은 readonly 값을 추가했습니다.
- 검증로직 Repository → Service 이동
    - 중복 예약 추가와 같은 예외 상황에서 예외 발생을 Repository에서 했는데 Service에서 하도록 구조를 변경했습니다. Repository는 DB 접근에만 집중하고, Service에서 비즈니스 관련 예외를 처리하기 위해 이와 같이 변경했습니다. 다만 Theme 삭제과정에서 해당 Theme으로 Reservation이 존재하면 예외처리를 해야하는 부분이 있는데, 이는 참조무결성 관련 예외이기 때문에 Repository에서 처리하도록 했습니다.
- Repository의 create 메서드의 이름 save로 변경
    - DB에 저장할 때는 create보다는 save의 의미가 더 맞는 것 같아서 이름을 변경했습니다.
- Dto 사용
    - 저번에 실무에서 DTO가 많이 사용된다고 말씀해주셔서 사용해봤습니다! 각 엔터티에 대해 Request와 Response를  만들었습니다. 변환은 서비스 계층에서 수행했습니다. 어디서 변환을 수행해야하는 지 고민이 좀 있었는데 Service에서 많이 수행하는 것 같아서 Service에서 변환을 수행했습니다! 또 각 도메인에서는 DTO의 존재를 모르게 하는 것이 좋을 것 같아서 dto 클래스에 entity로 변환하는 메서드(from / to)를 추가했습니다. 또, ReservationResponse는 해당 예약 테마의 모든 정보(이름, 상세정보, 가격)을 모두 가지고 있어야 해서 Reservation 엔터티에 더해 추가 정보를 가지고 있도록 했습니다.
- Service 계층 테스트 추가
    - Service에서 예외가 발생하는 상황에 대한 로직을 테스트하기 위해 Service 계층에 테스트를 추가했습니다. 단순히 Repository의 메서드를 통해 값을 Controller로 전달하는 성격의 메서드(ex. delete)는 테스트하지 않았습니다.
    
테스트 부분에서는 느낀 것이 테이블이 추가되면서 기존에 있던 테스트의 많은 코드가 바뀌어서 리팩터링 내성이 중요하겠다고 느꼈습니다. 더 좋은 테스트를 만드는 방법에 대한 학습도 중요하겠다고 생각했습니다.

2023-01-16 08:48 UTC, maythree requested changes
고생 많으셨습니다. 기술온보딩 처음 시작했을때보다 훨씬 코드 가독성이 좋아지셨네요👍👍
그럼 남겨놓은 리뷰사항들 확인하시어 수정 부탁드리겠습니다.

2023-01-16 08:48 UTC, maythree commented on src/main/java/nextstep/reservation/dto/ReservationResponse.java
> +    private final String name;
ThemeResponse랑 중복되는 정보들인 것 같네요. ThemeResponse 객체를 활용하시면 추후 테마 모델 관련 변경 시 변경 포인트가 줄어들 것 같네요.

2023-01-16 08:48 UTC, maythree commented on src/main/java/nextstep/reservation/repository/JdbcReservationRepository.java
> +    public Optional<Reservation> findById(long id) {
Optional로 바꾸셨네요.👍👍

2023-01-16 08:48 UTC, maythree commented on src/main/java/nextstep/reservation/service/ReservationService.java
> +        ThemeResponse foundedTheme = themeService.findById(savedReservation.getThemeId());
테마가 만일 존재하지 않을 경우, reservationRepository.save(reservationRequest.toEntity())는 이미 수행되었는데, 이 경우는 문제가 없을까요??

2023-01-16 08:48 UTC, maythree commented on src/main/java/nextstep/reservation/service/ReservationService.java
> +        if (optionalReservation.isEmpty()) {
Optional의 활용방법들에 대하여 좀 더 학습해보시고, 여기서는 orElseThrow를 활용해보시어도 좋으실 것 같습니다.

2023-01-16 08:48 UTC, maythree commented on src/main/java/nextstep/reservation/service/ReservationService.java
> +        return deleteRowNumber == 1;
테마서비스에서도 동일하게 사용되고도 있어서 1이라는 매직넘버보다는 의미있는 상수로 선언하여 사용되면 좋을 것 같네요.

2023-01-16 08:48 UTC, maythree commented on src/main/resources/schema.sql
> +    name  varchar(20),
모델에서는 nullable 선언이 안되어있는데, 여기에서는 nullable인 컬럼들이 여러개 보이네요. 혹시 그렇게 상이하게 하신 이유가 있으실까요?

2023-01-16 08:48 UTC, maythree commented on src/test/java/nextstep/reservation/ThemeRepositoryTest.java
> +        //given
given, when, then 구조를 주석으로 명시해주시어 테스트코드 가독성이 더욱 좋아졌네요👍

2023-01-16 08:48 UTC, maythree commented on src/test/java/nextstep/reservation/ThemeRepositoryTest.java
> +        this.theme = new Theme(null, "호러", "매우 무서운", 24000);
테스트 수행전 공통으로 theme를 생성하시어 모든 테스트가 같이 사용하고 있는데요.
생성에 비용이 많이 들거나, 다른 특별한 이유가 없으시다면 테스트별로 구성하여 테스트 간 격리가 이루어지는게 더욱 좋은 테스트코드일 것이라고 생각이 듭니다.
케이스마다 다르기 때문에 테스트 코드를 작성하실 때 중복 제거와 테스트 격리 두 가지 사이의 균형을 잘 잡으시는게 좋으실 것 같습니다.

2023-01-16 17:45 UTC, herbi1411 commented on src/main/java/nextstep/reservation/dto/ReservationResponse.java
> +    private final String name;
ReservationResponse 안에 ThemeResponse를 가지고 있게 하면 Theme에 대한 정보가 추가되는 상황에서도 유연하게 대처가 될 것 같습니다!! 해당 부분 수정했습니다. 수정하고 반환 데이터가 다음과 같이 변경 됐습니다.

변경 전

```json
{
    "id": 3,
    "date": "2022-08-12",
    "time": "13:00",
    "name": "name",
    "themeName": "워너고홈",
    "themeDesc": "병맛 어드벤처 회사 코믹물",
    "themePrice": 29000
}
```

변경 후

```json
{
    "id": 3,
    "date": "2022-08-12",
    "time": "13:00",
    "name": "name",
    "themeResponse": {
        "id": 3,
        "name": "워너고홈",
        "desc": "병맛 어드벤처 회사 코믹물",
        "price": 29000
    }
}
```

+) 수정한 이후에 과제 요구사항에서는 변경 전과 같은 스펙으로 반환을 요구해서 커스텀 시리얼라이저를 사용해서 ThemeResponse를 가져와보려고 구글링을 찾아봤는데 원하는 필드는 뽑아내는데 성공했지만 wrap돼있는 것을 뽑아내는데 실패했습니다!😢 결과적으로 현재는 다음과 같이 반환되는 형태입니다.

Custom Serializer 생성(Unwrapped 실패)

```java
{
    "id": 1,
    "date": "2022-08-12",
    "time": "13:00",
    "name": "name",
    "themeResponse": {
        "themeName": "워너고홈",
        "themeDesc": "병맛 어드벤처 회사 코믹물",
        "themePrice": 29000
    }
}
```

실무에 많이 쓰이는 지는 모르겠만 시리얼라이저를 통해 데이터를 다루는 개념도 추가로 더 공부해봐야 할 것 같습니다!!

2023-01-16 17:46 UTC, herbi1411 commented on src/main/java/nextstep/reservation/service/ReservationService.java
> +        ThemeResponse foundedTheme = themeService.findById(savedReservation.getThemeId());
심각한 버그가 있었네요.. 실제로 이런경우가 있으면 큰일날 것 같습니다. 테마를 찾는 과정에서 결과적으로 예외는 발생 되겠지만  그 전에 예약이 생성되는 문제가 생길 것 같아요. 테스트코드로 커버리지를 하지 못했습니다. 

예약 생성할 때 ReservationRepository에서 sql을 통해 테마가 존재하는 지 검사하도록 했습니다!! 서비스 계층에서 할까 하다가 이 부분도 참조무결성 관련 로직인 것 같아서 repository에서 수행했습니다! (원래대로면 테이블 생성할 때 외래키로 연결하면 될 것 같은데 이를 자바 코드로 직접 하려니까 새로운 경험을 하는 것 같습니다!)

2023-01-16 17:46 UTC, herbi1411 commented on src/main/java/nextstep/reservation/service/ReservationService.java
> +        if (optionalReservation.isEmpty()) {
Optional의 orElseThrow를 사용해서 가독성 좋은 코드를 만들 수 있네요. 좋은 메서드인 것 같습니다. 알려주셔서 감사합니다.😀

```java
@Transactional(readOnly = true)
    public ReservationResponse findById(long id) {
        Reservation reservation = reservationRepository.findById(id)
                .orElseThrow(() -> new RoomEscapeException(NO_SUCH_RESERVATION));
        ThemeResponse theme = themeService.findById(reservation.getThemeId());
        return ReservationResponse.from(reservation, theme);
    }
```

ThemeService에도 똑같이 쓰인 부분이 있어서 orElseThrow로 바꿨습니다!!

2023-01-16 17:46 UTC, herbi1411 commented on src/main/java/nextstep/reservation/service/ReservationService.java
> +        return deleteRowNumber == 1;
매직넘버를 사용하고 있었네요. 해당 상수가 여러 클래스에서 사용되고 있어서 Contstant 클래스를 하나 만들어서 상수를 선언했습니다!

2023-01-16 17:47 UTC, herbi1411 commented on src/main/resources/schema.sql
> +    name  varchar(20),
의도하지는 않았는데 모델 클래스에 nullable인지 아닌지 여부를 지정해주면 예상치못한 버그를 막을 수 있을 것 같습니다! 모든 필드에 널가능성 여부를 명시했습니다.

그리고 원래 저장을 위해 Repository에 모델객체를 전달할 때 모델의 id를 DB에서 받아와야해서 우선 null로 만들고 넘겨야 했기 때문에 nullable로 지정을 했습니다. 그런데 이번에 NonNull로 해야 예상치 못한 개발 오류를 막을 수 있지 않을까 생각을 해서 NonNull로 만들고 Repository로 넘겨줄때는 쓰레기 id값 (1L)을 만들어 넘겨주는 방식으로 해봤습니다. 이 방법도 사실 좋지는 않은 것 같네요.. ㅎ 그래도 피드백 덕분에 모델에 널 가능성 여부를 지정해서 버그 발생 가능성을 줄일 수 있다는 것을 알게됐습니다. 감사합니다!

2023-01-16 17:49 UTC, herbi1411 commented on src/test/java/nextstep/reservation/ThemeRepositoryTest.java
> +        this.theme = new Theme(null, "호러", "매우 무서운", 24000);
말씀해주신대로 setup 메서드를 없애고 각 테스트에서 필요 로직을 수행하도록 했습니다!
궁금한 것이 하나 있습니다! BeforeEach를 통해 제가 지정한 객체 생성 부분은 각 테스트마다 코드 실행 전에 이루어져 매번 객체가 생성되므로 테스트 격리가 이루어진다고 생각했는데 제가 잘못 이해했거나 알지 못한 다른 사이드 이펙트가 있는 것일까요??

2023-01-17 00:26 UTC, maythree commented on src/test/java/nextstep/reservation/ThemeRepositoryTest.java
> +        this.theme = new Theme(null, "호러", "매우 무서운", 24000);
음 격리의 용어적인 이해 차이가 있었네요. BeforeEach에 생성해놓은 테마 객체가 수정되게 되면 해당 클래스 내의 테스트 코드 모두 영향을 받게 되어 하나의 수정이 다른 테스트 모두에 영향을 줄 수 있어 유지보수성이 떨어질 수도 있다는 의미였습니다.

2023-01-17 00:30 UTC, maythree commented on src/main/resources/schema.sql
> +    name  varchar(20),
제가 전달드린 의도는 오히려 DB 스키마의 제약조건이 코드의 제약조건보다 더욱 닫혀있게 됨으로써 DB와 코드에서 제약조건이 이중으로 체크되면 좋다는 것을 알려드릴 의도였습니다. 아이디의 경우는 아이디를 쓰레기 id값으로 할 필요까지는 없을 것 같고 DB 스키마에만 not null 제약조건을 주셔도 될 것 같습니다. 비즈니스 레벨에서는 아이디는 null이 들어올수도 있는 것이니깐요.

2023-01-17 04:25 UTC, herbi1411 commented on src/main/resources/schema.sql
> +    name  varchar(20),
제가 거꾸로 이해했군요.  DB와 비즈니스 로직 상에서 이중으로 검사하면 더 안전하게 구성할 수 있을 것 같습니다. id 필드는 Nullable하게 이전처럼 수정했습니다! Reseravtion, Theme의 나머지 필드는 주어진 스키마로는 Nullable이지만 모두 Not null로 변경했고, 모델 클래스에서 NonNull 어노테이션으로 Nullable하지 않게 명시했습니다!

2023-01-17 04:29 UTC, herbi1411 commented on src/test/java/nextstep/reservation/ThemeRepositoryTest.java
> +        this.theme = new Theme(null, "호러", "매우 무서운", 24000);
아 이제 이해했습니다. BeforeEach의 Theme 객체를 생성하는 코드를 어떤 필요에 의해 변경하면 기존에 이를 사용하는 다른 테스트들에서 영향을 받을 수 있다는 말씀이시군요. 테스트에 따라서 객체 생성할 때 인자값이 달라질 수 도 있으므로 이는 분리하는게 맞는 것 같습니다. 어제 BeforeEach에서 공유 객체를 사용해놓지 않도록 반영해놔서 추가로 코드 수정은 하지 않았습니다!!

2023-01-17 05:26 UTC, maythree approved these changes
고생많으셨습니다👍👍

2023-01-17 05:26 UTC, merged