[Ayaan.jun] 방탈출 예약 관리 Step3 리뷰 요청 드립니다!
next-step/spring-roomesacpe-reservation-kakao pull request #88
Opened 2023-01-16 01:25 UTC by Neurumaru

방탈출 예약 관리 Step3 리뷰 요청 드립니다!

Controller - Service - Repository 구조로 했으며,
Controller에서는 필요한 작업을 맵핑해주고, 
Service에서는 한 트랜잭션 안에서 수행되어야하는 예외처리를 하도록 했습니다.
그리고 Repository (DAO) 는 데이터베이스와의 기본적인 통신만을 하도록 만들었습니다.

API는 JDBC를 이용해서 만들고 Console은 Connection을 이용해서 만들었는데,
Connection의 경우 사용이 불편해서 DAOManager를 만들어서 이를 이용해서 쿼리를 주고 받도록 만들었습니다.

추가로 과제를 진행하면서 궁금증이 들었던 부분이 있었습니다.
- Connection의 경우 일반적으로 언제 열어서 언제 닫는것이 옳은 건가요?
  - 계속해서 API를 주고 받는 경우에는 계속 열어두는게 좋을 듯 하면서도, Connection의 연결을 보장할 수 없을 것 같아 쿼리를 보낼 때마다 연결해야 될것 같기도 합니다. 혹시 현업에서는 어떤 방식으로 Connection을 관리하는지 궁금합니다.
- auto_increment되는 id를 테스트 해야한다고 하면 어떻게 하는지?
  - 테스트에 transactional 어노테이션을 사용하면 데이터베이스가 롤백이 된다고 들었는데, 문제는 auto_increment 에 대해서는 롤백이 되지 않았습니다. 
  - 저의 경우는 일단 테이블을 드랍하고 다시 만드는 작업을 통해서 auto_increment값을 유지 했습니다.
  - 다른 방법으로는 auto_increment값을 직접 재지정 해주는 작업을 통해서 유지시키거나 아예 id 값에 대해서 테스트를 진행하지 않는 방법들이 떠올랐습니다.

2023-01-18 09:35 UTC, hayden-ii requested changes
늦어져서 죄송합니다. 테스트에서 auto_increment id는 일반적으로 (이름 그대로) 해당 row에 대한 identification 용도일것으로 보이는데 해당 id 로 어떤 테스트를 진행하고 싶으신걸까요? auto_increment 값은 트랜잭션과 별도로 처리되는 값이라 트랙젝션이 롤백 되더라도 값은 감소되지 않는데, 꼭 테스트가 필요하다면 drop/create 말고 alter 요청으로 auto_increment 값을 조정할수 있긴 합니다~

2023-01-18 09:35 UTC, hayden-ii commented on src/main/java/roomescape/dao/DAOManager.java
> +public class DAOManager {
db connection을 관리해주는 클래스로 보이는데, data access object 를 관리하는 역할은 아닌것 같은데 요 부분 클래스 정의를 명확히 해줄수 있으면 좋겠습니다~

2023-01-18 09:35 UTC, hayden-ii commented on src/main/java/roomescape/dao/theme/ThemeDAO.java
> +    String ID_TABLE = "id";
theme table의 Id column 에 해당되는데, ID_TABLE 이라는 변수명이 조금 헷갈릴수 있을것 같습니다. 다른 이름을 써보면 어떨까요?

2023-01-18 09:35 UTC, hayden-ii commented on src/main/java/roomescape/console/view/InputView.java
> +    private static void printCommandHelp() {
공통되는 라인 함수화 👍

2023-01-18 09:35 UTC, hayden-ii commented on src/main/java/roomescape/controller/ConsoleControllerMapper.java
> +    public static void executeCommand(String input) {
input 요청에 따라 함수로 분리해서 구현 👍 (다른 로직이 추가되었을 경우를 대비해서, 하나가 맞으면 그 아래는 비교할필요가 없으니 return 해줘도 좋겠네요)

2023-01-18 09:35 UTC, hayden-ii commented on src/main/java/roomescape/dao/DAOManager.java
> +            return DriverManager.getConnection(url, user, password);
db connection 관련해서 질문 주셨는데, 일반적으로 db connection pool을 가지고 새로운 요청 시에 pool에서 connection을 빼서 사용해주는 걸로 알고 있습니다~ Database Connection Pool 관련해서 정리가 잘 된 글이 있으니 참고하시면 좋겠네요. https://linked2ev.github.io/spring/2019/08/14/Spring-3-%EC%BB%A4%EB%84%A5%EC%85%98-%ED%92%80%EC%9D%B4%EB%9E%80/

2023-01-18 09:35 UTC, hayden-ii commented on src/test/java/roomescape/service/exception/ReservationServiceExceptionTest.java
> +public class ReservationServiceExceptionTest {
예외 상황에 대한 테스트 추가 👍

2023-01-18 09:35 UTC, hayden-ii commented on src/main/java/roomescape/dao/DAOResult.java
> +public class DAOResult {
DAO 에서 1개의 값만 가지고 오는걸 확인하고 그 값을 리턴해주도록 되어있는데, 위의 DAOManager 과 동일하게 클래스에서 하는 동작과 이름이 조금 다르지않을까 싶습니다.

2023-01-19 01:13 UTC, Neurumaru commented on src/main/java/roomescape/dao/DAOManager.java
> +            return DriverManager.getConnection(url, user, password);
아하 이런방식으로 연결을 해두고 관리를 하는군요! 감사합니다! 😀
이부분을 한번 비슷하게 만들어봐야겠습니다!

2023-01-19 01:46 UTC, Neurumaru commented
괜찮습니다! 장애 끝난지 얼마 안되셔서 힘드실텐데 이렇게 리뷰 해주셔서 감사합니다!
ReservationController에서 반환되는 Location을 테스트 하기 위해서 id 값이 필요하다고 느꼈습니다.
그리고 find와 delete를 테스트 하기 위해서 id가 필요한데, Sql 어노테이션으로 생성하는 경우 id를 알기 힘들었습니다.
다른 방법으로는 create를 사용해서 생성하고 id를 가져오는 방법도 있을 듯 했지만, create도 테스트를 진행하는데 find와 delete를 위해서 create를 호출하는것이 좋은 단위테스트인가에 대한 의문이 들었습니다.

2023-01-24 16:51 UTC, Neurumaru commented
수정 후 다시 리뷰 요청 드립니다!

Connection을 DataSource를 이용해 DataSourceUtils에서 가져오도록 변경했습니다. 그리고 기존에 DAOManager에서 ConnectionManager로 이름을 변경했습니다.
그리고 RowMapper만 사용하지 않고, 단일 객체를 가져오는 경우에는 ResultSetExtractor, 객체 리스트를 가져오는 경우에는 RowMapper를 사용함으로써 이전에 말씀해 주셨던 DAOResult를 삭제했습니다.
마지막으로 대부분의 테스트에 대해서 Transactional을 이용해서 롤백해서 테스트를 진행하며, 예외적으로 테이블이 없는 경우를 테스트 할때만 rollback을 사용하지 않고 drop/create를 통해서 테스트를 진행하였습니다.

2023-01-30 04:40 UTC, hayden-ii approved these changes
확인이 늦어져서 죄송합니다. DB connection pool 을 사용하도록 변경해주셨군요 :) 👍 👍  수고하셨습니다!

2023-01-30 04:40 UTC, merged